### ISSUE TITLE
Infinite loop caused when particle.next points to itself

### ISSUE THREAD

**Issue by RestartMV** [pixijs/particle-emitter#128]
Under rare circumstances which I'm having trouble replicating (but which are probably related to killing multiple particles in the same frame with a particleLayer.children[i].kill() command), it's possible for the '.next' on a particle to be assigned to itself.  This means that when we get to this part of the emitter update code

```
Emitter.prototype.update = function (delta) {
        if (this._autoUpdate) {
            delta = delta / PIXI.settings.TARGET_FPMS / 1000;
        }
        //if we don't have a parent to add particles to, then don't do anything.
        //this also works as a isDestroyed check
        if (!this._parent)
            return;
        //update existing particles
        var i, particle, next;
        for (particle = this._activeParticlesFirst; particle; particle = next) {
            next = particle.next;
            particle.update(delta);
        }
```
It will fall into an infinite loop and never escape.

I don't think it's likely I'll be able to consistently replicate what causes this behavior (I suspect it's a weird race condition), but it seems like a quick check to make sure that a particle doesn't point to itself would prevent the infinite loop, at least.

**Comment by andrewstart** [comment]
Are you manually killing particles individually? Recycling (and spawning) of particles happens synchronously; they are immediately spliced out of/appended to their linked list with no recursion involved, so race conditions shouldn't be possible. In the current code, if a particle were to kill itself in its `update()` method when spawned (only possible with a custom Particle class), that would cause a bug where the particle is both 'active' and in the pool of unused particles.
If you can figure out the cause, I'd be happy to add in a fix, but as far as I know all the linked list stuff is handled correctly.

**Comment by RestartMV** [comment]
The only time I've spotting this happening is when the framerate is really tanking AND I spawn particles which are immediately destroyed, so I suppose it's possible they actually are dying when spawned.

I'm using the built-in functions to kill them - is there a safer way of specifying individual particles should be destroyed (like setting age to 9999 years or something so they get cleaned up next frame?)

**Comment by andrewstart** [comment]
The normal update method looks at the particle lifetime and skips particles that would die on their initial update. If they last long enough to get out of the (synchronous) particle spawning, they should be safe.
Using `kill()` to remove a particle _should_ be safe at basically any time other than that very first update, so I need to know more about your setup to consider any possible edge cases.

**Comment by RestartMV** [comment]
I've been loop through the particlelayer's .children list every frame, and children[i].kill() the particles that are colliding with things (based on the particle.x and particle.y).  

This is sitting on top of a big pile of javascript I didn't write, so I have no idea how my update function syncs up with pixi's update once the program gets so bogged down that frames start dropping (I found the particle bug by accident when doing a stress test with tons of interacting colliders, when a bunch of them ended up overlapping my particle emitter).  I'll see if I can come up with a reliable minimal test case.

**Comment by andrewstart** [comment]
That is definitely an advanced but expected use case that should work fine. Due to the way Javascript works, it is impossible for your update method to intersect with the emitter updat - everything runs one at a time, regardless of framerate.
I will ponder the code more, maybe I will find an edge case. On your end, I would suggest modifying the library code (whichever file is being pulled in by your build system) to have an `if` check for if a particle is pointing to itself after `kill()` and hit a `debugger;` statement. Maybe therr will be something unique about that particle, most likely its position in the emitters list (would have to save prev/next vals before killing it).
