### ISSUE TITLE
Support for PIXI v6 individual modules

### ISSUE THREAD

**Issue by qtiki** [pixijs/particle-emitter#151]
Using `pixi-particles` with the individual PIXI v6 modules is not possible at the moment because `index.d.ts` imports PIXI objects from the `pixi.js` bundle.

With v6 the individual packages have proper TypeScript types so it would be better to import these from the specific package, for example `import { Container } from '@pixi/display'`. This seems to be the "official" direction that other plugins are going as well.

**Comment by andrewstart** [comment]
[Release 5.0.0](https://github.com/pixijs/particle-emitter/releases/tag/v5.0.0) is out!
