### ISSUE TITLE
Project Name Confusion

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/particle-emitter#154]
This has been bothering me for awhile, there's some confusion between this library and the ParticleContainer package (`@pixi/particles`). I think we should disambiguate these two things more clearly by renaming one or both of these. "particles" is a little overloaded here.

Anyone have any ideas? I'm probably more inclined to change pixi-particles to something else as opposed to change ParticleContainer. Maybe `@pixi/emitter` or `@pixi/particle-simulation`?

**Comment by andrewstart** [comment]
I could live with `@pixi/emitter`, or `@pixi/particle-emitter` if you wanted to be explicit. That said, `@pixi/particles` probably causes its own confusion by only containing ParticleContainer with no way of actually generating particles.

**Comment by bigtimebuddy** [comment]
Good idea. I think this might be my preference:

| Before | After |
| --- | ---- |
| `@pixi/particles` | `@pixi/particle-container` |
| `pixi-particles` | `@pixi/particle-emitter` |

There's a relationship, but there are still two separate things.

**Comment by andrewstart** [comment]
Yeah, that's probably the clearest naming convention.

**Comment by bigtimebuddy** [comment]
Couple of follow-up tasks related to this:

* [ ] Rename Readme from "Pixi Particles" to "PixiJS Particle Emitter"
* [ ] Rename repo from `pixi-particles` to `particle-emitter`
* [ ] Update Readme and repo links to reflect new gh-pages URL
* [ ] Rename the dist files and  from `pixi-particles` to `particle-emitter`
* [ ] Fix links in docs/index.html
* [ ] Fix title in docs/examples/index.html
* [ ] Fix repo & bug links in package.json
* [ ] Publish latest version using `@pixi` scope

**Comment by bigtimebuddy** [comment]
:clap:
