### ISSUE TITLE
Class 'Container' defines instance member property 'renderCanvas', but extended class 'LinkedListContainer' defines it as in stance member function.

### ISSUE THREAD

**Issue by konan21** [pixijs/particle-emitter#160]
Hello. I found one issue with typing `Class 'Container' defines instance member property 'renderCanvas', but extended class 'LinkedListContainer' defines it as inst
ance member function.`

It happened in `pixi-particles/index.d.ts:854:2` when I try to build the project. 
And it's related to [`interface DisplayObject`](https://github.com/pixijs/pixijs/blob/main/packages/canvas/canvas-renderer/global.d.ts#L26)  and  [`LinkedListContainer.renderCanvas()`](https://github.com/pixijs/pixi-particles/blob/master/src/LinkedListContainer.ts#L800)

Of cource I can use `"skipLibCheck": true` in tsconfig.json to not check all d.ts files, but I know about the error :)

![image](https://user-images.githubusercontent.com/19189951/128871899-a7c68d1a-e205-419b-be01-a157f45df797.png)

![image](https://user-images.githubusercontent.com/19189951/128710905-c77be911-d25b-4c5b-80b3-a2fa0082b0ce.png)

Here is a repo to reproduce the error https://github.com/konan21/new_blank_pixijs_app

**Comment by andrewstart** [comment]
The current release doesn't support PixiJS 6 - you'll have to build the current master branch for that.

**Comment by konan21** [comment]
Do you plan to make a release version to support PixiJS 6 soon?

**Comment by andrewstart** [comment]
Soon-ish. I want to get https://github.com/pixijs/pixi-particles/pull/158 in to concentrate all the breaking changes into one release. The runtime is complete, but I want to finish the data provided for editor usage.

**Comment by andrewstart** [comment]
[Release 5.0.0](https://github.com/pixijs/particle-emitter/releases/tag/v5.0.0) is now out.
