### ISSUE TITLE
Spawn a single particle

### ISSUE THREAD

**Issue by hood** [pixijs/particle-emitter#161]
Picking up from where #131 left off, I'd like to be able to spawn a single particle from an emitter, even if this means setting up the emitter to always spawn a single particle.

**Comment by andrewstart** [comment]
The upcoming major update will have an `emitNow()` method that will emit a single wave of particles (one frequency tick, basically).

**Comment by andrewstart** [comment]
[Release 5.0.0](https://github.com/pixijs/particle-emitter/releases/tag/v5.0.0) is out, which has this!
