### ISSUE TITLE
404 for Interactive Particle Editor

### ISSUE THREAD

**Issue by MentalGear** [pixijs/particle-emitter#164]
The interactive editor as stated in the readme (http://pixijs.github.io/particle-emitter-editor/) resolves in a 404 error.

**Comment by andrewstart** [comment]
Whoops, that link got caught up in the find & replace renaming of the repo. Thanks for catching that!

**Comment by MentalGear** [comment]
The library.js file on the pixi editor shows version 3.0.4. Is that intentional ?

**Comment by andrewstart** [comment]
The editor is rather old and needs a complete overhaul. As such, it doesn't support all of the new features, but does produce emitter configuration that you can use with the `upgradeConfig()` function.
