### ISSUE TITLE
interactive editor examples in v5 format?

### ISSUE THREAD

**Issue by aMadReason** [pixijs/particle-emitter#171]
Hiya,

This is possibly a silly question and I'm probably missing something somewhere, but is there an interactive editor for the newer emitter formats? The examples from the current one don't use behaviours at all (even just a repo of the examples in the new format would be amazing).

using:
"pixi.js": "^6.2.1"
"@pixi/particle-emitter": "^5.0.3"

Thanks!

**Comment by andrewstart** [comment]
The runtime is backwards compatible with the older format, so you can use the editor if you want to. However, all of the examples in it, and more, [live in this repository already](https://github.com/pixijs/particle-emitter/tree/master/docs/examples)!

**Comment by aMadReason** [comment]
Knew I was being daft. Thanks @andrewstart !!
