### ISSUE TITLE
Update the example project with the new json config.

### ISSUE THREAD

**Issue by HowlingMadZ** [pixijs/particle-emitter#173]
I spent some 3 hours trying to figure out why the particle system wasn't working... until I finally went and noticed the examples code https://pixijs.io/particle-emitter/examples/fountain.html and the editor code both have the json in a different format from the one in the Readme https://github.com/pixijs/particle-emitter/blob/master/README.md

An alternative would be include both styles.

**Comment by andrewstart** [comment]
The examples do have the JSON in the latest format (with some older boilerplate to handle loading and playback), only the editor is out of date.

**Comment by andrewstart** [comment]
I've updated the readme with a note about the editor output needing an extra step to be usable.
