### ISSUE TITLE
IntColorComplex throws null exception

### ISSUE THREAD

**Issue by HowlingMadZ** [pixijs/particle-emitter#174]
![image](https://user-images.githubusercontent.com/6544536/156941638-8b960d70-e39d-4b3d-9943-3043f4c0e242.png)

Reproduction steps are as follows:

I created an effect with 3 colors 

`{
					"type": "color",
					"config": {
						"color": {
							"list": [
								{
									"time": 0,
									"value": "ffffff"
								},
								{
									"time": 0.5,
									"value": "ff00ff"
								},
								{
									"time": 1,
									"value": "9ff3ff"
								}
							]
						}
					}
				},`

Then i play the animation, tab out of the tab, and tab back in. When I get back, there is an exception and the entire system grinds to a halt (could be due to message amount in debug log)

If my color list has only two items (from time 0 to time 1) it works fine, it's when I added a third color that this exception happens on tabbing out.

**Comment by HowlingMadZ** [comment]
So today I tried to reproduce this issue again today, and I couldn't, so there must be another thing happening at the same time.

**Comment by andrewstart** [comment]
Good catch! There was an error when particles were spawned with behaviors using the linked list interpolation (3+ stages, not stepped) during a long frame. I've fixed it in version 5.0.4.
