### ISSUE TITLE
LinkedListContainer doesn't play nice with Destroy method

### ISSUE THREAD

**Issue by miltoncandelero** [pixijs/particle-emitter#179]
The destroy method for container has the line
`const oldChildren = this.removeChildren(0, this.children.length);`
however in a linkedList the children array always returns length zero (empty array).

This causes an _out of range_ exception in the removeChildren method

**Comment by andrewstart** [comment]
It took a minute to puzzle out why it was going wrong, but this has been fixed in v5.0.7!
