### ISSUE TITLE
Classes not invoked with new?

### ISSUE THREAD

**Issue by Ragers** [pixijs/particle-emitter#196]
Hi,

I am new to pixi.js and I am running through the tutorials to see the capabilities of pixi.js. In the tutorial this library gets mentioned.
But when I try to use (even your get started example) I get the following error:
`Class constructor Sprite cannot be invoked without 'new'`

It is being pointed to line `424` in `pixi-particles.es.js`.

Any feedback would be cool, as I would love to see this in action.

**Comment by andrewstart** [comment]
What version of PixiJS and this library are you using? Given that partial stack trace, I would assume a recent version of PixiJS and an older version of this library, and they are incompatible.

**Comment by andrewstart** [comment]
The library had a name change to `@pixi/particle-emitter`, so change to the latest release of that.
