### ISSUE TITLE
Alpha interpolating doesn't work for images

### ISSUE THREAD

**Issue by Namesnipes** [pixijs/particle-emitter#200]
On the old interactive website https://pixijs.io/pixi-particles-editor/#, setting alpha start to 1 and alpha end to 0 creates a smooth fade from visible to invisible. I took the JSON and used upgradeConfig() and everything is the same except the particles jump from fully visible to fully invisible.

I have also manually made the config with the same results.

Version: Pixi.js 7.1.2, particle-emitter 5.0.8

**Comment by andrewstart** [comment]
What are you using as a container for your particles?

**Comment by Namesnipes** [comment]
> What are you using as a container for your particles?

I was using ParticleContainer, I switched to Container and it's working fine now. Thanks! For anyone else, you can use ParticleContainer if you change the [tint property](https://pixijs.download/v5.0.0-alpha.2/docs/PIXI.ParticleContainer.html#ParticleContainer) to true.

Closed.
