### ISSUE TITLE
Best practice for continuous trail on a fast-moving object?

### ISSUE THREAD

**Issue by reececomo** [pixijs/particle-emitter#210]
Hey there 👋 

-I've got a fast-moving object (a ball)
- I'd like to draw a continuous trail behind it.
- Is that possible through `particle-emitter`? Attaching a standard emitter doesn't look great.

Is there a way to emit based on distance traveled, instead of once-per-draw-at-the-current-position?

Would the best alternative be drawing it manually using `PIXI.Graphics`?

### Example

(Excuse the bad MS Paint.)

![particles](https://github.com/pixijs/particle-emitter/assets/7390781/5f891f33-c62d-4508-a8cb-e4757fbe8c4f)

The top image is roughly 

> In ^this specific example, there's actually two emitters, but same applies for one emitter.

**Comment by reececomo** [comment]
(For reference, just increasing emission rate results in patchy trails like this:)

![image](https://github.com/pixijs/particle-emitter/assets/7390781/024f4e73-9b83-49bd-bfbb-d31710140257)

**Comment by reececomo** [comment]
Tinkered around with settings. Was using an interpolation renderer library, which I added support for `Emitter.setOwnerPos()` which prevented [the gaps](https://github.com/pixijs/particle-emitter/issues/210#issuecomment-1872785769).

Still not _great_, a little patchy, but looking a lot better now:

![image3](https://github.com/pixijs/particle-emitter/assets/7390781/2399e184-c34d-48fd-b501-86af410fe767)

**Comment by reececomo** [comment]
Another quick update: Performance is pretty horrendous on lower and middle-end devices, its only about ~2000 particles. Still investigating.

**Comment by andrewstart** [comment]
You can reduce the impact of this library on performance by using a LinkedListContainer (from this library) as the parent to your emitted particles. Basic particle emission will never get you a true trail, though, as that is typically a different mesh-based effect.

**Comment by reececomo** [comment]
Tinkering around with thicker particles and not changing the scale, just the alpha - got the number of particles down from ~2300 to around 500 which has improved performance for now.

> as that is typically a different mesh-based effect.

Ah thank you, that's probably a good place for me to look.

> You can reduce the impact of this library on performance by using a LinkedListContainer

Nice, will have a look at that too.

![image](https://github.com/pixijs/particle-emitter/assets/7390781/a2cd8774-119e-45d8-84c1-8410d62d83fb)
