### ISSUE TITLE
Issue with animation

### ISSUE THREAD

**Issue by peternikhil28** [pixijs/particle-emitter#74]
Animation of all the particles is not playing properly after 1st particle's lifetime gets over during emission.
If I increase lifetime of particles, animation plays properly for a longer time. That is duration of how much time animation plays properly differs with lifetime of particle.

**Comment by andrewstart** [comment]
Do you have an example of this behavior that I can inspect?

**Comment by peternikhil28** [comment]
Yes. Please check the attachment.

After 8 sec, that is the minimum lifetime, animation is not 
proper.

Another issue which I saw was for addAtBack. Just examine what happens if you make addAtBack true for the same code. You can see that animation is not proper till the emission ends. 
[Test.zip](https://github.com/pixijs/pixi-particles/files/1567638/Test.zip)

**Comment by andrewstart** [comment]
Sorry that this got left for a while, I missed your response.
Bad news: This is some odd behavior that I don't know how to fix (but am currently looking at).
Good news: This is specific to ParticleContainers - if you change your parent to be a regular PIXI.Container it'll work fine.

**Comment by andrewstart** [comment]
For the time being, I've removed the special handling for ParticleContainers in version 3 - it'll work the same as a Container, although the performance may not be better.
