### ISSUE TITLE
support for "image zone"

### ISSUE THREAD

**Issue by ramarro123** [pixijs/particle-emitter#76]
hi, i find a particle system that have a cool feature that they call "image zone"

unfortunately i don't find definition nor seems highly supported

the "image zone" feature, seems to create a sort of path based on a png, considering the "colored" area (or the non transpared one) as a emitter zone, or emitter area.

http://a-jie.github.io/Proton/example/zone/imagezone/imagezone.html
http://a-jie.github.io/Proton/example/render/pixel/google.html

do you think that you will eventually support such feature? or have an idea on how i can achive a similar result?

**Comment by andrewstart** [comment]
The first example could be created by making a subclass of `Emitter` and adding a new emission type (point, circle, burst, etc) that emits based on some paths - setting that up would be a little complicated, but doable. The second example is very complicated, and is unlikely to ever be supported in this library.

**Comment by andrewstart** [comment]
Closing this due to age, but with [release 5.0.0](https://github.com/pixijs/particle-emitter/releases/tag/v5.0.0) writing a custom spawning behavior is easier than ever.
