### ISSUE TITLE
Sub-emitters?

### ISSUE THREAD

**Issue by digilocker** [pixijs/particle-emitter#92]
I was wondering if there was an easier way of possibly adding sub emitters?  I had an idea for a fireball effect with the fireballs being the main particles then a smoke trail following their position.

Had a trial yesterday and managed to get something working but required quite a few workarounds using timers to check the last particle added etc..

Any easier ways something similar could be achieved that I am missing, or is it a feature that could possibly be added?

http://www.html5gamedevs.com/topic/42106-pixi-particles-and-subemitters/

**Comment by andrewstart** [comment]
I had considered making a subclass of Particle that owns an Emitter and updates it automatically, which should do the trick. Unfortunately, I currently don't have the time to do so, but that is the road that I would try to go down.

**Comment by digilocker** [comment]
Awesome, thanks for the update, just wanted to make sure I wasn't missing a trick :)

**Comment by andrewstart** [comment]
This is now easy to make with the behaviors in [release 5.0.0](https://github.com/pixijs/particle-emitter/releases/tag/v5.0.0).

**Comment by tankorsmash** [comment]
@andrewstart  I'm looking through the behaviors. Would the recommended way of creating subemitters be through a second `PointSpawn`? I looked through a few examples in the README and I didn't see any that appear to use subemitters.

**Comment by andrewstart** [comment]
There is no concept of subemitters in this library, you would instead use two Emitters as subemitters controlled by your "super emitter" that you create.

**Comment by tankorsmash** [comment]
Thanks! Does that mean there's no builtin [behavior](https://pixijs.io/particle-emitter/docs/modules/behaviors.html) to help to achieve this?

 Maybe a better way to frame my question is: what in the 5.0.0 release made it easier to make that parent-sub1-sub2 emitter combination? It's not clear which of the [behaviors](https://pixijs.io/particle-emitter/docs/modules/behaviors.html) listed would help with that. It probably exists (hence the earlier comment), but I'm missing a step!

**Comment by andrewstart** [comment]
Yes, that's exactly it: you would make your own behavior that creates and manages another Emitter.

**Comment by tankorsmash** [comment]
Thanks again for your help!
